# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'iosDemo' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)



end
